from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
    initial=True
    dependencies=[('auth','0012_alter_user_first_name_max_length')]
    operations=[
        migrations.CreateModel(name='Profile',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('role',models.CharField(choices=[('buyer','Buyer'),('seller','Seller'),('both','Buyer & Seller')],default='buyer',max_length=12)),('phone',models.CharField(blank=True,max_length=30)),('whatsapp',models.CharField(blank=True,max_length=30)),('business_name',models.CharField(blank=True,max_length=160)),('state',models.CharField(blank=True,max_length=80)),('city',models.CharField(blank=True,max_length=100)),('bio',models.TextField(blank=True)),('avatar',models.ImageField(blank=True,null=True,upload_to='avatars/')),('verified',models.BooleanField(default=False)),('created_at',models.DateTimeField(auto_now_add=True)),('user',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='profile',to='auth.user'))]),
        migrations.CreateModel(name='Ad',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=160)),('image',models.ImageField(blank=True,null=True,upload_to='ads/')),('target_url',models.URLField(blank=True)),('active',models.BooleanField(default=True)),('priority',models.PositiveIntegerField(default=0)),('created_at',models.DateTimeField(auto_now_add=True))],options={'ordering':['-priority','-created_at']}),
        migrations.CreateModel(name='Tile',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=180)),('slug',models.SlugField(blank=True,max_length=50,unique=True)),('brand',models.CharField(max_length=120)),('category',models.CharField(choices=[('floor','Floor Tiles'),('wall','Wall Tiles'),('porcelain','Porcelain Tiles'),('ceramic','Ceramic Tiles'),('marble','Marble Look'),('mosaic','Mosaic'),('outdoor','Outdoor Tiles'),('bathroom','Bathroom Tiles'),('kitchen','Kitchen Tiles'),('paving','Paving Tiles')],max_length=30)),('description',models.TextField()),('size',models.CharField(max_length=80)),('color',models.CharField(blank=True,max_length=80)),('finish',models.CharField(choices=[('glossy','Glossy'),('matt','Matt'),('polished','Polished'),('satin','Satin'),('textured','Textured'),('anti-slip','Anti-slip')],default='matt',max_length=30)),('material',models.CharField(default='Porcelain',max_length=100)),('tiles_per_box',models.PositiveIntegerField(default=1)),('coverage_per_box',models.DecimalField(decimal_places=2,default=1,max_digits=7)),('stock_boxes',models.PositiveIntegerField(default=0)),('price_per_box',models.DecimalField(decimal_places=2,max_digits=12)),('price_per_sqm',models.DecimalField(blank=True,decimal_places=2,max_digits=12,null=True)),('min_order',models.PositiveIntegerField(default=1)),('state',models.CharField(choices=[(s,s) for s in ['Abia','Adamawa','Akwa Ibom','Anambra','Bauchi','Bayelsa','Benue','Borno','Cross River','Delta','Ebonyi','Edo','Ekiti','Enugu','Gombe','Imo','Jigawa','Kaduna','Kano','Katsina','Kebbi','Kogi','Kwara','Lagos','Nasarawa','Niger','Ogun','Ondo','Osun','Oyo','Plateau','Rivers','Sokoto','Taraba','Yobe','Zamfara','Federal Capital Territory']],max_length=80)),('city',models.CharField(max_length=100)),('area',models.CharField(blank=True,max_length=120)),('phone',models.CharField(blank=True,max_length=30)),('whatsapp',models.CharField(blank=True,max_length=30)),('video_url',models.URLField(blank=True)),('featured',models.BooleanField(default=False)),('verified',models.BooleanField(default=False)),('status',models.CharField(choices=[('published','Published'),('pending','Pending'),('soldout','Sold Out'),('draft','Draft')],default='published',max_length=20)),('views',models.PositiveIntegerField(default=0)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('seller',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='tiles',to='auth.user'))],options={'ordering':['-featured','-created_at'],'indexes':[models.Index(fields=['brand','category'],name='market_tile_brand_c_5c3f4b_idx'),models.Index(fields=['state','city'],name='market_tile_state_c_efbd57_idx'),models.Index(fields=['price_per_box'],name='market_tile_price_p_0a6f7d_idx')]}),
        migrations.CreateModel(name='TileMedia',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('kind',models.CharField(choices=[('image','Image'),('video','Video')],default='image',max_length=10)),('image',models.ImageField(blank=True,null=True,upload_to='tiles/images/%Y/%m/')),('video',models.FileField(blank=True,null=True,upload_to='tiles/videos/%Y/%m/')),('external_url',models.URLField(blank=True)),('caption',models.CharField(blank=True,max_length=160)),('created_at',models.DateTimeField(auto_now_add=True)),('tile',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='media',to='market.tile'))]),
        migrations.CreateModel(name='Favorite',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('tile',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='favorites',to='market.tile')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='tile_favorites',to='auth.user'))],options={'constraints':[models.UniqueConstraint(fields=('user','tile'),name='unique_tile_favorite')]}),
        migrations.CreateModel(name='TileLike',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('tile',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='likes',to='market.tile')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='auth.user'))],options={'constraints':[models.UniqueConstraint(fields=('user','tile'),name='unique_tile_like')]}),
        migrations.CreateModel(name='Comment',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('body',models.TextField()),('created_at',models.DateTimeField(auto_now_add=True)),('approved',models.BooleanField(default=True)),('tile',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='comments',to='market.tile')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='auth.user'))]),
        migrations.CreateModel(name='Question',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('body',models.TextField()),('answer',models.TextField(blank=True)),('answered_at',models.DateTimeField(blank=True,null=True)),('created_at',models.DateTimeField(auto_now_add=True)),('asker',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='questions_asked',to='auth.user')),('tile',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='questions',to='market.tile'))]),
        migrations.CreateModel(name='Conversation',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('updated_at',models.DateTimeField(auto_now=True)),('created_at',models.DateTimeField(auto_now_add=True)),('participants',models.ManyToManyField(related_name='tile_conversations',to='auth.user')),('tile',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='conversations',to='market.tile'))]),
        migrations.CreateModel(name='ChatMessage',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('body',models.TextField()),('read',models.BooleanField(default=False)),('created_at',models.DateTimeField(auto_now_add=True)),('conversation',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='messages',to='market.conversation')),('sender',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='auth.user'))]),
        migrations.CreateModel(name='Inquiry',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('quantity',models.PositiveIntegerField(default=1)),('message',models.TextField()),('status',models.CharField(choices=[('new','New'),('contacted','Contacted'),('closed','Closed')],default='new',max_length=20)),('created_at',models.DateTimeField(auto_now_add=True)),('buyer',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='auth.user')),('tile',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='inquiries',to='market.tile'))]),
        migrations.CreateModel(name='Notification',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=160)),('body',models.TextField()),('url',models.CharField(blank=True,max_length=255)),('read',models.BooleanField(default=False)),('created_at',models.DateTimeField(auto_now_add=True)),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='tile_notifications',to='auth.user'))]),
        migrations.CreateModel(name='SavedSearch',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=100)),('query',models.JSONField(default=dict)),('created_at',models.DateTimeField(auto_now_add=True)),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='saved_searches',to='auth.user'))]),
    ]
