# Generated by Django 5.2.17 on 2026-09-24 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="tile",
            new_name="market_tile_brand_c5f424_idx",
            old_name="market_tile_brand_c_5c3f4b_idx",
        ),
        migrations.RenameIndex(
            model_name="tile",
            new_name="market_tile_state_87302c_idx",
            old_name="market_tile_state_c_efbd57_idx",
        ),
        migrations.RenameIndex(
            model_name="tile",
            new_name="market_tile_price_p_eef78c_idx",
            old_name="market_tile_price_p_0a6f7d_idx",
        ),
    ]
