from django.contrib import admin
from .models import *
@admin.register(Profile)
class ProfileAdmin(admin.ModelAdmin): list_display=('user','business_name','role','state','verified'); list_filter=('role','verified','state'); search_fields=('user__username','business_name','phone')
@admin.register(Tile)
class TileAdmin(admin.ModelAdmin): list_display=('name','brand','category','state','city','price_per_box','stock_boxes','status','featured','verified'); list_filter=('category','brand','state','status','featured','verified'); search_fields=('name','brand','city','area','description'); prepopulated_fields={'slug':('name',)}
@admin.register(TileMedia)
class TileMediaAdmin(admin.ModelAdmin): list_display=('tile','kind','created_at')
@admin.register(Favorite)
class FavoriteAdmin(admin.ModelAdmin): list_display=('user','tile','created_at')
@admin.register(TileLike)
class TileLikeAdmin(admin.ModelAdmin): list_display=('user','tile','created_at')
@admin.register(Comment)
class CommentAdmin(admin.ModelAdmin): list_display=('tile','user','approved','created_at'); list_filter=('approved',)
@admin.register(Question)
class QuestionAdmin(admin.ModelAdmin): list_display=('tile','asker','answered_at','created_at')
@admin.register(Conversation)
class ConversationAdmin(admin.ModelAdmin): list_display=('tile','updated_at')
@admin.register(ChatMessage)
class ChatMessageAdmin(admin.ModelAdmin): list_display=('conversation','sender','read','created_at')
@admin.register(Inquiry)
class InquiryAdmin(admin.ModelAdmin): list_display=('tile','buyer','quantity','status','created_at'); list_filter=('status',)
@admin.register(Ad)
class AdAdmin(admin.ModelAdmin): list_display=('title','active','priority','created_at'); list_filter=('active',)
@admin.register(Notification)
class NotificationAdmin(admin.ModelAdmin): list_display=('user','title','read','created_at'); list_filter=('read',)
@admin.register(SavedSearch)
class SavedSearchAdmin(admin.ModelAdmin): list_display=('user','name','created_at')
admin.site.site_header='Tilespot Administration'; admin.site.site_title='Tilespot Admin'; admin.site.index_title='Manage Tilespot Marketplace'
